#!/usr/bin/env python3
# MIT License
#
# Copyright (c) 2026- pyannote.audio contributors
#
# Emit C++ translation units with community-1 defaults for ``cpp-annote-cli`` /
# ``CppAnnote``: receptive field JSON, pipeline snapshot JSON, golden speaker bounds JSON,
# and raw tensors from HF ``xvec_transform.npz`` / ``plda.npz`` (same checkpoint as ONNX export).
#
# Run automatically after ``export_segmentation_onnx.py`` / ``export_embedding_onnx.py``, or:
#   python cpp/scripts/export_cpp_annote_embedded.py --repo-root .

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


def _pick_token(explicit: str | None) -> str | bool | None:
    if explicit:
        return explicit
    env = os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN")
    if env:
        return env
    return None


def _format_double_array(name: str, arr) -> str:
    flat = arr.astype("float64").reshape(-1)
    body = ",\n  ".join(repr(float(v)) for v in flat)
    return f"// {name} length={flat.size}\nalignas(64) const double {name}[{flat.size}] = {{\n  {body}\n}};"


def _format_float_array(name: str, arr) -> str:
    flat = arr.astype("float32").reshape(-1)
    body = ",\n  ".join(repr(float(v)) + "f" for v in flat)
    return f"// {name} length={flat.size}\nalignas(64) const float {name}[{flat.size}] = {{\n  {body}\n}};"


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate community1_cpp_annote_embedded.{h,cpp} for C++ defaults.")
    ap.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parent.parent.parent)
    ap.add_argument(
        "--golden-root",
        type=Path,
        default=None,
        help="Directory with receptive_field.json and pipeline_snapshot.json (default: <repo>/cpp/golden/callhome_eng_idx0)",
    )
    ap.add_argument(
        "--golden-utterance",
        type=Path,
        default=None,
        help="Utterance dir with golden_speaker_bounds.json (default: <golden-root>/callhome_eng_data_idx0_head120s)",
    )
    ap.add_argument("--checkpoint", default="pyannote/speaker-diarization-community-1")
    ap.add_argument("--revision", default=None)
    ap.add_argument("--token", default=None)
    args = ap.parse_args()

    repo: Path = args.repo_root.resolve()
    golden_root = args.golden_root or (repo / "cpp" / "golden" / "callhome_eng_idx0")
    utter = args.golden_utterance or (golden_root / "callhome_eng_data_idx0_head120s")

    rf_path = golden_root / "receptive_field.json"
    snap_path = golden_root / "pipeline_snapshot.json"
    bounds_path = utter / "golden_speaker_bounds.json"
    for p in (rf_path, snap_path, bounds_path):
        if not p.is_file():
            raise SystemExit(f"missing golden file: {p}")

    rf_txt = rf_path.read_text(encoding="utf-8").strip()
    snap_txt = snap_path.read_text(encoding="utf-8").strip()
    bounds_txt = bounds_path.read_text(encoding="utf-8").strip()

    try:
        from huggingface_hub import hf_hub_download
    except ImportError as e:
        raise SystemExit("Install huggingface_hub: pip install huggingface_hub") from e

    token = _pick_token(args.token)
    kw = dict(repo_id=args.checkpoint, repo_type="model", token=token)
    if args.revision:
        kw["revision"] = args.revision
    xv_path = Path(hf_hub_download(filename="plda/xvec_transform.npz", **kw))
    pl_path = Path(hf_hub_download(filename="plda/plda.npz", **kw))

    import numpy as np

    xv = np.load(str(xv_path))
    pl = np.load(str(pl_path))
    mean1 = np.asarray(xv["mean1"], dtype=np.float64)
    mean2 = np.asarray(xv["mean2"], dtype=np.float32)
    lda = np.asarray(xv["lda"], dtype=np.float32)
    mu = np.asarray(pl["mu"], dtype=np.float64)
    tr = np.asarray(pl["tr"], dtype=np.float64)
    psi = np.asarray(pl["psi"], dtype=np.float64)

    out_hdr = repo / "cpp" / "src" / "community1_cpp_annote_embedded.h"
    out_cpp = repo / "cpp" / "src" / "community1_cpp_annote_embedded.cpp"

    def esc_c_raw(s: str) -> str:
        if ")]'" not in s and ")]'\"" not in s:
            return f'R"pyannote_embed({s})pyannote_embed"'
        raise SystemExit("golden text contains delimiter sequence )]'  — adjust export_cpp_annote_embedded.py")

    hpp = f"""// SPDX-License-Identifier: MIT
// AUTO-GENERATED by cpp/scripts/export_cpp_annote_embedded.py — do not edit by hand.
#pragma once

#include <cstddef>

namespace pyannote::embedded_community1 {{

extern const char receptive_field_json[];
extern const std::size_t receptive_field_json_size;
extern const char pipeline_snapshot_json[];
extern const std::size_t pipeline_snapshot_json_size;
extern const char golden_speaker_bounds_json[];
extern const std::size_t golden_speaker_bounds_json_size;

extern const double xvec_mean1[{mean1.size}];
extern const float xvec_mean2[{mean2.size}];
extern const float xvec_lda[{lda.size}];
extern const double plda_mu[{mu.size}];
extern const double plda_tr[{tr.size}];
extern const double plda_psi[{psi.size}];

constexpr int kEmbeddingDim = {int(mean1.size)};
constexpr int kLdaOutDim = {int(mean2.size)};
constexpr int kPldaDim = {int(mu.size)};

}}  // namespace pyannote::embedded_community1
"""

    cpp = f"""// SPDX-License-Identifier: MIT
// AUTO-GENERATED by cpp/scripts/export_cpp_annote_embedded.py — do not edit by hand.

#include <cstddef>

#include "community1_cpp_annote_embedded.h"

namespace pyannote::embedded_community1 {{

const char receptive_field_json[] = {esc_c_raw(rf_txt)};
const std::size_t receptive_field_json_size = sizeof(receptive_field_json) - 1;

const char pipeline_snapshot_json[] = {esc_c_raw(snap_txt)};
const std::size_t pipeline_snapshot_json_size = sizeof(pipeline_snapshot_json) - 1;

const char golden_speaker_bounds_json[] = {esc_c_raw(bounds_txt)};
const std::size_t golden_speaker_bounds_json_size = sizeof(golden_speaker_bounds_json) - 1;

{_format_double_array("xvec_mean1", mean1)}

{_format_float_array("xvec_mean2", mean2)}

{_format_float_array("xvec_lda", lda)}

{_format_double_array("plda_mu", mu)}

{_format_double_array("plda_tr", tr)}

{_format_double_array("plda_psi", psi)}

}}  // namespace pyannote::embedded_community1
"""

    out_hdr.write_text(hpp, encoding="utf-8")
    out_cpp.write_text(cpp, encoding="utf-8")
    print(f"Wrote {out_hdr}")
    print(f"Wrote {out_cpp}")


if __name__ == "__main__":
    main()
