// SPDX-License-Identifier: MIT
// AUTO-GENERATED by cpp/scripts/export_ort_embedded.py — do not edit by hand.
#ifndef COMMUNITY1_ORT_EMBEDDED_H_
#define COMMUNITY1_ORT_EMBEDDED_H_

#include <cstddef>

namespace cppannote::embedded_community1 {

extern const unsigned char segmentation_ort_data[];
extern const std::size_t segmentation_ort_data_size;

extern const unsigned char embedding_ort_data[];
extern const std::size_t embedding_ort_data_size;

extern const char segmentation_json[];
extern const std::size_t segmentation_json_size;

extern const char embedding_json[];
extern const std::size_t embedding_json_size;

}  // namespace cppannote::embedded_community1

#endif  // COMMUNITY1_ORT_EMBEDDED_H_
