// SPDX-License-Identifier: MIT
// AUTO-GENERATED by cpp/scripts/export_cpp_annote_embedded.py — do not edit by
// hand.
#ifndef COMMUNITY1_CPP_ANNOTE_EMBEDDED_H_
#define COMMUNITY1_CPP_ANNOTE_EMBEDDED_H_

#include <cstddef>

namespace cppannote::embedded_community1 {

extern const char receptive_field_json[];
extern const std::size_t receptive_field_json_size;
extern const char pipeline_snapshot_json[];
extern const std::size_t pipeline_snapshot_json_size;
extern const char golden_speaker_bounds_json[];
extern const std::size_t golden_speaker_bounds_json_size;

extern const double xvec_mean1[256];
extern const float xvec_mean2[128];
extern const float xvec_lda[32768];
extern const double plda_mu[128];
extern const double plda_tr[16384];
extern const double plda_psi[128];

constexpr int kEmbeddingDim = 256;
constexpr int kLdaOutDim = 128;
constexpr int kPldaDim = 128;

}  // namespace cppannote::embedded_community1

#endif  // COMMUNITY1_CPP_ANNOTE_EMBEDDED_H_
